language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6.10'
before_script:
  - npm run lint
after_success:
  - npm version patch -m "Updating version to $s for publishing"
  - npm publish