language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js:
  - '6.10'
before_script:
  - npm run lint
before_install: 
  - npm install -g npm@'>=3'
after_success:
  - npm run ci-publish || true
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
